main(): Open repository even if PWD is a subdirectory
Previously, running `git todo` outside the root of the repository would
result in this error:

    error: unable to open repository: could not find repository from '.'; class=Repository (6); code=NotFound (-3)

It turns out the `open()` method expects the given path to be the
repository root. Use `open_from_env()` instead, which functions more
like regular Git commands.